version: "3.6"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000 &
             celery -A app worker -l info"
  rabbit:
    image: 'rabbitmq:3-management'
    ports:
        # The standard AMQP protocol port
      - '5672:5672'
        # HTTP management UI
      - '15672:15672'