# Generated by Django 3.2.5 on 2021-08-18 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=25)),
                ('file_path', models.CharField(max_length=255)),
                ('moved_to', models.CharField(max_length=20)),
                ('received_timestamp', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('uuid', models.CharField(max_length=32)),
                ('event_type', models.CharField(max_length=25)),
                ('elapsed_time', models.CharField(max_length=45)),
                ('event_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='core.event')),
            ],
        ),
    ]
